@Webhooks_HostAddress = http://localhost:5166/api

### Create Subscription
POST {{Webhooks_HostAddress}}/webhooks/subscriptions
Content-Type: application/json

{
  "eventType": "order.created",
  "webhookUrl": "https://webhook.site/80f9855c-f819-4977-82b6-b837b5e3e84f"
}

### Get All Subscriptions
GET {{Webhooks_HostAddress}}/webhooks/subscriptions

### Create Order
POST {{Webhooks_HostAddress}}/orders
Content-Type: application/json

{
  "customerName": "Demo User",
  "amount": "123.45"
}

### Get All Orders
GET {{Webhooks_HostAddress}}/orders